### ISSUE TITLE
Getting an error with Redux-toolkit , "The object notation for `createSlice.extraReducers` has been removed

### ISSUE THREAD

**Issue by Manish-Sgh** [TheLegion007/JobFind-App#1]
# ERROR
The object notation for `createSlice.extraReducers` has been removed. Please use the 'builder callback' notation instead: https://redux-toolkit.js.org/api/createSlice
    at buildReducer (http://localhost:3000/static/js/bundle.js:54383:17)
    at reducer (http://localhost:3000/static/js/bundle.js:54410:33)
    at http://localhost:3000/static/js/bundle.js:62539:26
    at Array.forEach (<anonymous>)
    at assertReducerShape (http://localhost:3000/static/js/bundle.js:62537:25)
    at combineReducers (http://localhost:3000/static/js/bundle.js:62573:5)
    at configureStore (http://localhost:3000/static/js/bundle.js:53848:73)
    at ./src/store.js (http://localhost:3000/static/js/bundle.js:1790:79)
    at options.factory (http://localhost:3000/static/js/bundle.js:65163:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:64578:33

**Comment by Manish-Sgh** [comment]
updated code commit   : https://github.com/TheLegion007/JobFind-App/commit/e3f87b8d8b812ee276384cdfdf10fc10571e5424
