### ISSUE TITLE
Cannot destructure property 'user' of '(0 , react_redux__WEBPACK_IMPORTED_MODULE_3__.useSelector)(...)' as it is undefined. TypeError: Cannot destructure property 'user' of '(0 , react_redux__WEBPACK_IMPORTED_MODULE_3__.useSelector)(...)' as it is undefined.

### ISSUE THREAD

**Issue by Manish-Sgh** [TheLegion007/JobFind-App#2]
Cannot destructure property 'user' of '(0 , react_redux__WEBPACK_IMPORTED_MODULE_3__.useSelector)(...)' as it is undefined.
TypeError: Cannot destructure property 'user' of '(0 , react_redux__WEBPACK_IMPORTED_MODULE_3__.useSelector)(...)' as it is undefined.
    at NavBar (http://localhost:3000/main.6e2b8153c74778113b2a.hot-update.js:32:5)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:27368:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:30248:24)

issue arising in
 `const Navbar = () => {`
  `const { user } = useSelector((store) => store.redux);`
  ` const dispatch = useDispatch();`

**Comment by Manish-Sgh** [comment]
- proper path and, 
- state name which is used in redux should be correct while using useSelector .

_In NavBar.js_ 

`const { user } = useSelector((store) => store.user);`
corrected redux to user. 

commit id : 09b5a26e1838d2b4df09d2c666e58df72a88466a
